version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - sqlite_data:/app/api/data
    environment:
      - NODE_ENV=production
      - DB_FILE_NAME
      - BETTER_AUTH_SECRET
      - RESEND_API_KEY
      - BETTER_AUTH_URL
      - BETTER_AUTH_TRUSTED_ORIGINS
    restart: always

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file: .env
    ports:
      - "3006:80"
    depends_on:
      - api
    restart: always

volumes:
  sqlite_data:
    driver: local
